SQL_KEYWORDS = [
    'TABLE',
    'TABLESPACE',
    'PROCEDURE',
    'FUNCTION',
    'TRIGGER',
    'KEY',
    'VIEW',
    'MATERIALIZED VIEW',
    'LIBRARYDATABASE LINK',
    'DBLINK',
    'INDEX',
    'CONSTRAINT',
    'TRIGGER',
    'USER',
    'SCHEMA',
    'DATABASE',
    'PLUGGABLE DATABASE',
    'BUCKET',
    'CLUSTER',
    'COMMENT',
    'SYNONYM',
    'TYPE',
    'JAVA',
    'SESSION',
    'ROLE',
    'PACKAGE',
    'PACKAGE BODY',
    'OPERATORSEQUENCE',
    'RESTORE POINT',
    'PFILE',
    'CLASS',
    'CURSOR',
    'OBJECT',
    'RULE',
    'USER',
    'DATASET',
    'DATASTORE',
    'COLUMN',
    'FIELD',
    'OPERATOR',
    'SHUTDOWN',
]

SQL_REGEX = [
    "(?i)(.*)(\\b)+(OR|AND)(\\s)+(true|false)(\\s)*(.*)",
    "(?i)(.*)(\\b)+(OR|AND)(\\s)+(\\w)(\\s)*(\\=)(\\s)*(\\w)(\\s)*(.*)",
    "(?i)(.*)(\\b)+(OR|AND)(\\s)+(equals|not equals)(\\s)+(true|false)(\\s)*(.*)",
    "(?i)(.*)(\\b)+(OR|AND)(\\s)+([0-9A-Za-z_'][0-9A-Za-z\\d_']*)(\\s)*(\\=)(\\s)*([0-9A-Za-z_'][0-9A-Za-z\\d_']*)(\\s)*(.*)",
    "(?i)(.*)(\\b)+(OR|AND)(\\s)+([0-9A-Za-z_'][0-9A-Za-z\\d_']*)(\\s)*(\\!\\=)(\\s)*([0-9A-Za-z_'][0-9A-Za-z\\d_']*)(\\s)*(.*)",
    "(?i)(.*)(\\b)+(OR|AND)(\\s)+([0-9A-Za-z_'][0-9A-Za-z\\d_']*)(\\s)*(\\<\\>)(\\s)*([0-9A-Za-z_'][0-9A-Za-z\\d_']*)(\\s)*(.*)",
    "(?i)(.*)(\\b)+SELECT(\\b)+\\s.*(\\b)(.*)",
    "(?i)(.*)(\\b)+SELECT(\\b)+\\s.*(\\b)+FROM(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+INSERT(\\b)+\\s.*(\\b)+INTO(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+UPDATE(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+DELETE(\\b)+\\s.*(\\b)+FROM(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+UPSERT(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+SAVEPOINT(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+CALL(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+ROLLBACK(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+KILL(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+DROP(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+CREATE(\\b)+(\\s)*(" +
    "|".join(SQL_KEYWORDS) + ")(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+ALTER(\\b)+(\\s)*(" +
    "|".join(SQL_KEYWORDS) + ")(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+TRUNCATE(\\b)+(\\s)*(" +
    "|".join(SQL_KEYWORDS) + ")(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+LOCK(\\b)+(\\s)*(" + "|".join(SQL_KEYWORDS) + ")(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+UNLOCK(\\b)+(\\s)*(" +
    "|".join(SQL_KEYWORDS) + ")(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+RELEASE(\\b)+(\\s)*(" +
    "|".join(SQL_KEYWORDS) + ")(\\b)+\\s.*(.*)",
    "(?i)(.*)(\\b)+DESC(\\b)+(\\w)*\\s.*(.*)",
    "(?i)(.*)(\\b)+DESCRIBE(\\b)+(\\w)*\\s.*(.*)",
    "(.*)(/\\*|\\*/|;){1,}(.*)",
    "(.*)(-){2,}(.*)",
]

UNIX_ALIASES = ['ls', 'dir', 'pwd', 'cd', 'mkdir', 'rmdir', 'cp', 'mv', 'rm', 'touch','cat', 'less', 'head', 'tail', 'grep', 'find', 'awk', 'sed', 'top',
                'ps', 'kill', 'chmod', 'chown', 'tar', 'gzip', 'gunzip', 'zip', 'unzip','ping', 'ifconfig', 'netstat', 'route', 'traceroute', 'iptables', 'ssh',
                'scp', 'ftp', 'telnet', 'whoami', 'su', 'sudo', 'passwd', 'uname', 'date',
                'uptime', 'history', 'echo', 'man', 'whereis', 'which', 'locate', 'file','stat', 'df', 'du', 'free', 'w', 'finger', 'last', 'killall', 'htop',
                'nc', 'nmap', 'tcpdump', 'dig', 'host', 'nslookup', 'whois', 'curl', 'wget','git', 'svn', 'rsync', 'make', 'gcc', 'g++', 'python', 'python3', 'perl',
                'ruby', 'php', 'java', 'javac', 'node', 'npm', 'docker', 'docker-compose','netcat', 'ncat', 'socat', 'ssh', 'ssh-keygen', 'ssh-copy-id', 'ssh-agent',]

PATH_TRAVERSAL_REGEX = "/\.\./|\.\./|\.\%2f|/\.\%2f|/\.\\./|/\.\\.\\|/\.\\%5c/|/\%5c\.\\|/\%5c\.%2f"
